// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package io.github.ctlove0523.javasamples.grpc;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
