// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package io.github.ctlove0523.javasamples.grpc;

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.HelloResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
